version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: webmaster_db
      POSTGRES_USER: webmaster_user
      POSTGRES_PASSWORD: webmaster_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U webmaster_user -d webmaster_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=webmaster_db
      - DB_USER=webmaster_user
      - DB_PASSWORD=webmaster_password
      - DB_PORT=5432
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: python app.py

volumes:
  postgres_data:


